name: GitHub Actions Demo

on: [push]  # Trigger on every push to any branch

jobs:
  test-job:
    runs-on: ubuntu-latest  # Use Linux environment
    steps:
      - name: Print a message
        run: echo "Workflow triggered by a push event."

      - name: Print OS info
        run: echo "Running on: ${{ runner.os }}"

      - name: Print branch name
        run: echo "Branch: ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List project files
        run: ls ${{ github.workspace }}
